WIP: Initial
edgefarm/meta-edgefarm pull request #1
Opened 2022-01-05 14:25 UTC by KairaMiu

2022-01-24 14:35 UTC, KlausPopp commented on README.md
> +See [build instructions](https://github.com/ci4rail/yocto-images/tree/cleanup#building) from Ci4Rail repository for build definitons and scripts for yocto builds.
must be changed to main branch finally

2022-01-24 14:36 UTC, KlausPopp requested changes

2022-01-24 14:36 UTC, KlausPopp commented on README.md
> +# meta-ci4rail-bsp
Change to meta-edgefarm

2022-01-24 14:36 UTC, KlausPopp commented on README.md
> +This layer also includes images prepared for the Ci4Rail supported HW devices.
Is that true?

2022-01-25 10:40 UTC, KairaMiu commented on README.md
> +# meta-ci4rail-bsp
argf

2022-01-25 10:40 UTC, KairaMiu commented on README.md
> +See [build instructions](https://github.com/ci4rail/yocto-images/tree/cleanup#building) from Ci4Rail repository for build definitons and scripts for yocto builds.
done

2022-01-25 10:41 UTC, KairaMiu commented on README.md
> +# meta-ci4rail-bsp
done

2022-01-25 10:42 UTC, KairaMiu commented on README.md
> +This layer also includes images prepared for the Ci4Rail supported HW devices.
Isn't it? 
Reference: `recipes-images/images/edgefarm-image.bb`

2022-01-25 10:43 UTC, KairaMiu commented on README.md
> +This layer also includes images prepared for the Ci4Rail supported HW devices.
maybe this sentence is just confusing?

2022-01-25 13:54 UTC, KlausPopp approved these changes

2022-01-25 13:59 UTC, merged